# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cristian Cortez
email: cortez.cristian@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Serial entrepreneur & Full-stack developer.
  Trainer on new technologies and creator of @emprendevs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cortezcristian.github.io" # the base hostname & protocol for your site
twitter_username: cortezcristian
github_username: cortezcristian

# Build settings
markdown: kramdown

# Extra
exclude: [README.md, package.json, bower.json, Gruntfile.js, node_modules, .bowerrc]
